[package]
name = "benitoite-l-core"
description = ""
authors = ["0xDimay <HexDimay@yandex.ru>"]
version = "0.0.1"
edition = "2024"
rust-version = "1.95.0"
readme = "README.md"
license = "Apache-2.0"

[features]
log = ["dep:log"]

[dependencies]
anyhow = "1.0.102"
log = { version = "0.4.32", optional = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
async-std = "1.13.2"
sqlx = { version = "0.9", features = [ "runtime-async-std", "sqlite" ] }
url = "2.5.8"

[dev-dependencies]
env_logger = "0.11.10"
